### ISSUE TITLE
Unable to install packages via Yarn

### ISSUE THREAD

**Issue by MarkAPhillips** [michielbouw/react-typescript-yarn-lerna-monorepo-eslint-prettier-boilerplate#1]
When running Yarn install  error message 
"Workspaces can only be enabled in private projects" 

Resolved via setting private to true in main package.json

@michielbouw  - thanks for all your work on this - exactly what I was looking for - I will be running through it over the next few days so if I get any other issues will let you know.

**Comment by michielbouw** [comment]
Thank you for letting me know, I have been blindly using this private: true in the packages I have used this setup, so I didn't find that. 

I will update that.
